# Site settings
title: tqsunsetwiki
url: "https://tqsunset.github.io"
baseurl: ""
description: >
    Personal Wiki

# My information
email: 
author: tqsunset
profile: 
twitter_username: 
github_username: tqsunset
comment-support: 

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: tqsunset
  shortname: tqsunset
utterances:
  repo: tqsunset/tqsunset.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/tqsunset/tqsunset.github.io/blame/master/_wiki"
edit: "https://github.com/tqsunset/tqsunset.github.io/edit/master/_wiki"
issue: "https://github.com/tqsunset/tqsunset.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
